<a href="https://colab.research.google.com/github/psg0104-01/AI-project/blob/main/1_Numpy_%EC%88%98%EC%B9%98_%EA%B3%84%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
'''
✅ NumPy의 핵심 기능
기능	설명
다차원 배열(ndarray)	일반 리스트보다 훨씬 빠르고 효율적인 배열 구조를 제공함
벡터화 연산	for문 없이 배열 간 덧셈, 뺄셈, 곱셈 등을 빠르게 수행
브로드캐스팅(Broadcasting)	배열의 크기가 달라도 자동으로 계산을 맞춰줌
과학/수학 함수 내장	평균, 합계, 표준편차, 최대/최소값 등 다양한 함수 포함
배열 생성 함수	zeros, ones, arange, linspace 등 편리하게 배열 생성
선형대수 기능	행렬 곱, 역행렬, 전치, 고유값 등 수학적 계산 가능
파일 입출력	텍스트나 바이너리 형식의 배열 저장 및 불러오기 지원

⭐ NumPy의 주요 장점
장점	설명
빠른 연산 속도	내부적으로 C언어로 구현되어 파이썬 기본 리스트보다 훨씬 빠름
코드 간결성	반복문 없이 간단하게 배열 계산 가능 (코드가 짧고 읽기 쉬움)
메모리 절약	데이터 타입이 고정되어 있고, 리스트보다 메모리 사용량이 적음
다양한 수학 기능 지원	과학, 공학, AI, 통계 분야에 필요한 기능 대부분 포함
확장성	pandas, matplotlib, tensorflow 등 다른 유명 라이브러리와 잘 통합됨

'''

'\n✅ NumPy의 핵심 기능\n기능\t설명\n다차원 배열(ndarray)\t일반 리스트보다 훨씬 빠르고 효율적인 배열 구조를 제공함\n벡터화 연산\tfor문 없이 배열 간 덧셈, 뺄셈, 곱셈 등을 빠르게 수행\n브로드캐스팅(Broadcasting)\t배열의 크기가 달라도 자동으로 계산을 맞춰줌\n과학/수학 함수 내장\t평균, 합계, 표준편차, 최대/최소값 등 다양한 함수 포함\n배열 생성 함수\tzeros, ones, arange, linspace 등 편리하게 배열 생성\n선형대수 기능\t행렬 곱, 역행렬, 전치, 고유값 등 수학적 계산 가능\n파일 입출력\t텍스트나 바이너리 형식의 배열 저장 및 불러오기 지원\n\n⭐ NumPy의 주요 장점\n장점\t설명\n빠른 연산 속도\t내부적으로 C언어로 구현되어 파이썬 기본 리스트보다 훨씬 빠름\n코드 간결성\t반복문 없이 간단하게 배열 계산 가능 (코드가 짧고 읽기 쉬움)\n메모리 절약\t데이터 타입이 고정되어 있고, 리스트보다 메모리 사용량이 적음\n다양한 수학 기능 지원\t과학, 공학, AI, 통계 분야에 필요한 기능 대부분 포함\n확장성\tpandas, matplotlib, tensorflow 등 다른 유명 라이브러리와 잘 통합됨\n\n'

In [18]:
import numpy as np


'''
Numpy  배열 (array) - 숙제 : 배열과 list차이에 대해서 입력하기

'''

'\nNumpy  배열 (array) - 숙제 : 배열과 list차이에 대해서 입력하기\n\n'

In [10]:
#list는 수치해석에 불편하다
a = [1,3,5]
b = [2,4,6]
print(a[0]+ b[0])
print(a[1]+ b[1])
print(a[2]+ b[2])
print(a+b) # +연산:결합만 해준다
#print(a*b)

#for문을 쓰면 계산은 가능하다
res = [0,0,0]
for i in range(len(a)):
  res[i] = a[i] + b[i]
print('range(len(a)):',res)

res2 = []
for i in range(len(a)):
  res2.append(a[i]+b[i])
print('append:',res2)

res3 = []
for x,y in zip(a,b):  # zip(a,b) 쌍으로 묶어서 x,y에 넘겨준다.
  res3.append(x+y)
print('zip:', res3)

#이래서 Numpy가 필요하다!!!!
import numpy as np
a = np.array([1,3,5])
b = np.array([2,4,6])
print(a+b)
print(a*b)
print(a/b)

data = np.array([10,20,30])
print(data +5)
print(np.mean(data))

3
7
11
[1, 3, 5, 2, 4, 6]
range(len(a)): [3, 7, 11]
append: [3, 7, 11]
zip: [3, 7, 11]
[ 3  7 11]
[ 2 12 30]
[0.5        0.75       0.83333333]
[15 25 35]
20.0


In [158]:
#Numpy 배열의 차원(n-차원,shape)

#0 - 차원 array(스칼라, Scalar)


arr = np.array(100)
print(arr)
print(np.shape(arr)) #() 튜플로 반환 빈튜플로 반환(0차원)
print(np.ndim(arr))

print("___________________________1차원__________________________________")

#1-차원 array(백터, Vector)
#1차원 배열을 백터 라고 하며, 일렬로 저장, 가장 많이 사용한다.

arr1 = np.array([2,4,6,8,10])
print('Data type:',type(arr1))
print(arr,np.shape(arr1)) #(5, )
print(np.ndim(arr1)) #ndim: nth - dimension

print("----1차원 초기화 지정----")

#1차원배열 생성하면서 초기값 지정할수 있다
print(np.zeros(5)) #0.0으로 채워진 5개 요소의 1차원 배열
print(np.ones(5))
print(np.empty(5)) #현재 메모리에 남아 있는 "쓰레기값(Garbage)"을 그대로 사용
print(np.full(5,99))
print(np.arange(5)) #arange: array - range
print(np.arange(1,11,2))
print(np.random.random(15)) #0~1사이
print(np.linspace(0,100, num = 33)) #linear - space, 균일한 간격
print(arr1*10) #벡터화 연산(1차원 배열을 한꺼번에 계산한다.)

print("___________________________2차원__________________________________")

#2-차원 배열(행렬, matrix): 엑셀(행:row, 열:column)
arr2d = np.array([[2,4,6], [1,3,5]]) # 2행 3열 2차원 배열
print(arr2d)
print(np.shape(arr2d))
print(np.ndim(arr2d))
print(len(arr2d)) #행의 개수
print(len(arr2d[0])) #열의 개수
print(arr2d.size) #모든 요소의 개수

# 0부터 시작하는 정수 6개를 생성(arange)함수 2행 3열로 2차원 배열로 변환
np.arange(6).reshape(2,3)

print("----2차원 초기화 지정----")

#2차원도 초기화 지정 가능
print(np.zeros((2,3)))
print(np.ones((2,3)))
print(np.empty((2,3)))
print(np.full((2,3),99))
print(np.arange(6).reshape(2,3)) # 0~5까지의 6개의 정수를 2해 3열로 재배열
print(np.arange(1,13,2).reshape(2,3))
print(np.random.random((2,3))) # 2행 3열의 난수를 0~1미만 범위로 랜덤 생성
print(np.linspace(0,100, num = 6).reshape(2,3)) #linear-space, 균일한 간격, 2행 3열에 넣어준다
print('reshape -1 option:',np.linspace(0,100, num =33).reshape(-1,3)) # -1 option 자동으로 맞춰준다

print("___________________________3차원__________________________________")
# 3-차원 배열(텐서, Tensor)
# 3차원은 깊이(depth), 행(row), 열(column)로 구성, AI에서 주로 사용되는 Tensor의 기본구조
#머신러닝/딥러닝 등 에서 사용

arr3d = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
print(arr3d)
print(np.shape(arr3d),np.ndim(arr3d))  # (2,2,3) --> (depth,row,colum)

print(len(arr3d))
print(len(arr3d[0]))
print(len(arr3d[0][0]))
print(arr3d.size)


100
()
0
___________________________1차원__________________________________
Data type: <class 'numpy.ndarray'>
100 (5,)
1
----1차원 초기화 지정----
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[99 99 99 99 99]
[0 1 2 3 4]
[1 3 5 7 9]
[0.71669741 0.92942958 0.23340614 0.99642425 0.78049519 0.20669022
 0.35163381 0.7692929  0.93057749 0.23843693 0.96426843 0.98053121
 0.53945165 0.29614647 0.33525286]
[  0.      3.125   6.25    9.375  12.5    15.625  18.75   21.875  25.
  28.125  31.25   34.375  37.5    40.625  43.75   46.875  50.     53.125
  56.25   59.375  62.5    65.625  68.75   71.875  75.     78.125  81.25
  84.375  87.5    90.625  93.75   96.875 100.   ]
[ 20  40  60  80 100]
___________________________2차원__________________________________
[[2 4 6]
 [1 3 5]]
(2, 3)
2
2
3
6
----2차원 초기화 지정----
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[99 99 99]
 [99 99 99]]
[[0 1 2]
 [3 4 5]]
[[ 1  3  5]
 [ 7  9 11]]
[[0.19603452 0.37791842 0.40994969]
 [0.17566386 0.

In [160]:
#Array함수: flatten(): 배열을 1차원으로 펼치기
#flatten()은 다차원 배열을  1차원 벡터로 평탄화 하는 속성
#원본 배열은 그대로이고, 배열을 생성

arrflat = np.array([[1,2,3],[4,5,6]])
result = arrflat.flatten()
print(result)

#transpose(): 전치: 행 <->열 교환
#transpose()는 2차원 이상의 배열에서 행과 열을 바꿔주는 속성
#선형대수나 이미지 처리등에서 자주사용한다.
arrtrans = np.array([[1,2,3],[4,5,6]])
result = arrtrans.transpose()
print(result)

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
